version: 2.1

jobs:
  build-for-linux:
    docker: 
      - image: dreladen/ffxi_server
        auth:
          username: dreladen
          password: bc05b596-03dd-478b-9b90-ce742706744b

    steps:
      - checkout
      - run: pip3 install -r tools/requirements.txt
      - run: cp conf/default/* conf/
      - run: cp scripts/settings/default/* scripts/settings/
      - run: mkdir build
      - run: cd build
      - run: ls ../project
      - run: cmake ../project
      - run: make -j 4

workflows:
  version: 2.1 
  build:
    jobs:
      - build-for-linux